blocked_domains:
  - "indeed.com"
  - "glassdoor.com"
  - "ziprecruiter.com"
  - "monster.com"
  - "dice.com"
  - "careerbuilder.com"
  - "simplyhired.com"
  - "linkedin.com/jobs"
  - "hired.com"
  - "angel.co"
  - "wellfound.com"

blocked_usernames:
  - "indeed"
  - "glassdoor"
  - "ziprecruiter"
  - "monster_jobs"
  - "dice_jobs"
  - "careerbuilder"
  - "jobsearchbot"
  - "hiringbot"
  - "recruitmentbot"

blocked_companies:
  - "Robert Half"
  - "Randstad"
  - "Adecco"
  - "ManpowerGroup"
  - "Kelly Services"
  - "Hays"
  - "Michael Page"
  - "Kforce"
  - "TEKsystems"
  - "Insight Global"
  - "Apex Systems"
  - "Cyient"
  - "Collabera"
  - "Infosys BPM"
  - "Wipro"
  - "HCL"
  - "TCS"
